
CREATE TABLE TEST_SETTINGS (
      PREFERENCENAME VARCHAR2(100) NOT NULL,
      VALUE VARCHAR2(100),
      DEFAULTVALUE VARCHAR2(100),
      TYPE VARCHAR2(50) NOT NULL,
      STATUS VARCHAR2(50) NOT NULL,
      DESCRIPTION VARCHAR2(4000)
);
